//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sphere10.AutoMouse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sphere10.AutoMouse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.IO.UnmanagedMemoryStream LeftClickDown {
            get {
                return ResourceManager.GetStream("LeftClickDown", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream LeftClickUp {
            get {
                return ResourceManager.GetStream("LeftClickUp", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon MouseLeftButton {
            get {
                object obj = ResourceManager.GetObject("MouseLeftButton", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MouseLMRSettingsAid {
            get {
                object obj = ResourceManager.GetObject("MouseLMRSettingsAid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon MouseMiddleButton {
            get {
                object obj = ResourceManager.GetObject("MouseMiddleButton", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon MouseNoButton {
            get {
                object obj = ResourceManager.GetObject("MouseNoButton", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon MouseRightButton {
            get {
                object obj = ResourceManager.GetObject("MouseRightButton", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream RightClickDown {
            get {
                return ResourceManager.GetStream("RightClickDown", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream RightClickUp {
            get {
                return ResourceManager.GetStream("RightClickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TXT_About {
            get {
                return ResourceManager.GetString("TXT_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string TXT_Activate {
            get {
                return ResourceManager.GetString("TXT_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity By Weekday.
        /// </summary>
        public static string TXT_ActivityByWeekday {
            get {
                return ResourceManager.GetString("TXT_ActivityByWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stretches.
        /// </summary>
        public static string TXT_AllStretches {
            get {
                return ResourceManager.GetString("TXT_AllStretches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string TXT_Application {
            get {
                return ResourceManager.GetString("TXT_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Analysis.
        /// </summary>
        public static string TXT_Application_Analysis {
            get {
                return ResourceManager.GetString("TXT_Application_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms.
        /// </summary>
        public static string TXT_Arms {
            get {
                return ResourceManager.GetString("TXT_Arms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Click.
        /// </summary>
        public static string TXT_Auto_Click {
            get {
                return ResourceManager.GetString("TXT_Auto_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically click the mouse when mouse stops moving.
        /// </summary>
        public static string TXT_Automatically_Click_The_Mouse_When_Mouse_Stops_Moving {
            get {
                return ResourceManager.GetString("TXT_Automatically_Click_The_Mouse_When_Mouse_Stops_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically send a click when the mouse stops moving.
        /// </summary>
        public static string TXT_Automatically_Send_A_Click_When_Mouse_Stops_Moving {
            get {
                return ResourceManager.GetString("TXT_Automatically_Send_A_Click_When_Mouse_Stops_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Count.
        /// </summary>
        public static string TXT_Average_Count {
            get {
                return ResourceManager.GetString("TXT_Average_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Count.
        /// </summary>
        public static string TXT_AverageCount {
            get {
                return ResourceManager.GetString("TXT_AverageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Average Key Press Duration.
        /// </summary>
        public static string TXT_AverageKeyPressDuration {
            get {
                return ResourceManager.GetString("TXT_AverageKeyPressDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Mouse Click Duration.
        /// </summary>
        public static string TXT_AverageMouseClickDuration {
            get {
                return ResourceManager.GetString("TXT_AverageMouseClickDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Pressed Duration.
        /// </summary>
        public static string TXT_AveragePressedDuration {
            get {
                return ResourceManager.GetString("TXT_AveragePressedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TXT_Back {
            get {
                return ResourceManager.GetString("TXT_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse...
        /// </summary>
        public static string TXT_Browse {
            get {
                return ResourceManager.GetString("TXT_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string TXT_BuyNow {
            get {
                return ResourceManager.GetString("TXT_BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A serious error occured with the activation process. Please make sure you have Administrator privileges before trying to activate this software..
        /// </summary>
        public static string TXT_CannotWriteKeyInRegistry {
            get {
                return ResourceManager.GetString("TXT_CannotWriteKeyInRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string TXT_CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("TXT_CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TXT_Close {
            get {
                return ResourceManager.GetString("TXT_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string TXT_Contents {
            get {
                return ResourceManager.GetString("TXT_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Help.
        /// </summary>
        public static string TXT_ContextHelp {
            get {
                return ResourceManager.GetString("TXT_ContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string TXT_Count {
            get {
                return ResourceManager.GetString("TXT_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string TXT_Day {
            get {
                return ResourceManager.GetString("TXT_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Usage Overview.
        /// </summary>
        public static string TXT_DeviceUsageOverview {
            get {
                return ResourceManager.GetString("TXT_DeviceUsageOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click.
        /// </summary>
        public static string TXT_Double_Click {
            get {
                return ResourceManager.GetString("TXT_Double_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your RSI Warrior Activation Key:.
        /// </summary>
        public static string TXT_EnterRegoCode {
            get {
                return ResourceManager.GetString("TXT_EnterRegoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire History.
        /// </summary>
        public static string TXT_EntireHistory {
            get {
                return ResourceManager.GetString("TXT_EntireHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position monitor 18&quot; to 24&quot; away (an arm length) and about 15° to 13° below your line of sight.
        /// </summary>
        public static string TXT_ErgoWizardA {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t let light shine in your eyes or on your screen.
        /// </summary>
        public static string TXT_ErgoWizardB {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square screen to your line of vision.
        /// </summary>
        public static string TXT_ErgoWizardC {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forearms 90° from your spine.
        /// </summary>
        public static string TXT_ErgoWizardD {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thighs 90°  from your spine.
        /// </summary>
        public static string TXT_ErgoWizardE {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a well-made adjustable office chair.
        /// </summary>
        public static string TXT_ErgoWizardF {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a wrist pad to support your hands when not typing.
        /// </summary>
        public static string TXT_ErgoWizardG {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet flat on the floor.
        /// </summary>
        public static string TXT_ErgoWizardH {
            get {
                return ResourceManager.GetString("TXT_ErgoWizardH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes.
        /// </summary>
        public static string TXT_Eyes {
            get {
                return ResourceManager.GetString("TXT_Eyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Bad RSI.
        /// </summary>
        public static string TXT_For_Bad_RSI {
            get {
                return ResourceManager.GetString("TXT_For_Bad_RSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Preventing RSI.
        /// </summary>
        public static string TXT_For_Preventing_RSI {
            get {
                return ResourceManager.GetString("TXT_For_Preventing_RSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Recovering from RSI.
        /// </summary>
        public static string TXT_For_Recovering_From_RSI {
            get {
                return ResourceManager.GetString("TXT_For_Recovering_From_RSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string TXT_Fri {
            get {
                return ResourceManager.GetString("TXT_Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TXT_General {
            get {
                return ResourceManager.GetString("TXT_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic Mean Duration.
        /// </summary>
        public static string TXT_HarmonicMeanDuration {
            get {
                return ResourceManager.GetString("TXT_HarmonicMeanDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Analysis.
        /// </summary>
        public static string TXT_Historical_Analysis {
            get {
                return ResourceManager.GetString("TXT_Historical_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often would you like stretching breaks presened to you?.
        /// </summary>
        public static string TXT_How_Often_Would_You_Like_Stretching_Breaks_Presented_To_You {
            get {
                return ResourceManager.GetString("TXT_How_Often_Would_You_Like_Stretching_Breaks_Presented_To_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string TXT_Key {
            get {
                return ResourceManager.GetString("TXT_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Analysis.
        /// </summary>
        public static string TXT_Keyboard_Analysis {
            get {
                return ResourceManager.GetString("TXT_Keyboard_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Presses.
        /// </summary>
        public static string TXT_KeyPresses {
            get {
                return ResourceManager.GetString("TXT_KeyPresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Button.
        /// </summary>
        public static string TXT_Left_Button {
            get {
                return ResourceManager.GetString("TXT_Left_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        public static string TXT_Legs {
            get {
                return ResourceManager.GetString("TXT_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me know if I&apos;m accumulating too much hand strain.
        /// </summary>
        public static string TXT_Let_Me_Know_If_Im_Accumulating_Too_Much_Hand_Strain {
            get {
                return ResourceManager.GetString("TXT_Let_Me_Know_If_Im_Accumulating_Too_Much_Hand_Strain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load RSI Warrior on machine startup.
        /// </summary>
        public static string TXT_LoadRSIWarriorOnMachineStartup {
            get {
                return ResourceManager.GetString("TXT_LoadRSIWarriorOnMachineStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pressed Duration.
        /// </summary>
        public static string TXT_MaxPressedDuration {
            get {
                return ResourceManager.GetString("TXT_MaxPressedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Button.
        /// </summary>
        public static string TXT_Middle_Button {
            get {
                return ResourceManager.GetString("TXT_Middle_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Pressed Duration.
        /// </summary>
        public static string TXT_MinPressedDuration {
            get {
                return ResourceManager.GetString("TXT_MinPressedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string TXT_Mon {
            get {
                return ResourceManager.GetString("TXT_Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Active Application.
        /// </summary>
        public static string TXT_MostActiveApplication {
            get {
                return ResourceManager.GetString("TXT_MostActiveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Analysis.
        /// </summary>
        public static string TXT_Mouse_Analysis {
            get {
                return ResourceManager.GetString("TXT_Mouse_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Button.
        /// </summary>
        public static string TXT_MouseButton {
            get {
                return ResourceManager.GetString("TXT_MouseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Clicks.
        /// </summary>
        public static string TXT_MouseClicks {
            get {
                return ResourceManager.GetString("TXT_MouseClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        public static string TXT_Neck {
            get {
                return ResourceManager.GetString("TXT_Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Available.
        /// </summary>
        public static string TXT_NoDataAvailable {
            get {
                return ResourceManager.GetString("TXT_NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clicks and presses by week day.
        /// </summary>
        public static string TXT_Number_Of_Clicks_And_Presses_By_Week_Day {
            get {
                return ResourceManager.GetString("TXT_Number_Of_Clicks_And_Presses_By_Week_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clicks and presses for entire history.
        /// </summary>
        public static string TXT_Number_Of_Clicks_And_Presses_For_Entire_History {
            get {
                return ResourceManager.GetString("TXT_Number_Of_Clicks_And_Presses_For_Entire_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clicks and presses by week day.
        /// </summary>
        public static string TXT_NumberOfClicksAndPressesByWeekDay {
            get {
                return ResourceManager.GetString("TXT_NumberOfClicksAndPressesByWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clicks and presses for entire history.
        /// </summary>
        public static string TXT_NumberOfClicksAndPressesForEntireHistory {
            get {
                return ResourceManager.GetString("TXT_NumberOfClicksAndPressesForEntireHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string TXT_Other {
            get {
                return ResourceManager.GetString("TXT_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string TXT_Overview {
            get {
                return ResourceManager.GetString("TXT_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string TXT_PercentageSymbol {
            get {
                return ResourceManager.GetString("TXT_PercentageSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of RSI Warrior is a pirated copy. We cannot continue to make great ergonomics software for RSI Prevention and Recovery without your support. Please buy a legitamit copy today!.
        /// </summary>
        public static string TXT_PirateVersion {
            get {
                return ResourceManager.GetString("TXT_PirateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Stretch.
        /// </summary>
        public static string TXT_Random_Stretch {
            get {
                return ResourceManager.GetString("TXT_Random_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must install the full version of RSI Warrior. Please follow the instructions from the email/booklet you received with your registered copy of RSI Warrior..
        /// </summary>
        public static string TXT_RegisteredTrial {
            get {
                return ResourceManager.GetString("TXT_RegisteredTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Posture.
        /// </summary>
        public static string TXT_Remind_Posture {
            get {
                return ResourceManager.GetString("TXT_Remind_Posture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me to correct seating posture.
        /// </summary>
        public static string TXT_RemindMeToCorrectSeatingPosture {
            get {
                return ResourceManager.GetString("TXT_RemindMeToCorrectSeatingPosture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitive Strain Injury Monitoring.
        /// </summary>
        public static string TXT_Repetitive_Strain_Injury_Monitoring {
            get {
                return ResourceManager.GetString("TXT_Repetitive_Strain_Injury_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Button.
        /// </summary>
        public static string TXT_Right_Button {
            get {
                return ResourceManager.GetString("TXT_Right_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSI Alert!.
        /// </summary>
        public static string TXT_RSI_Alert {
            get {
                return ResourceManager.GetString("TXT_RSI_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string TXT_Sat {
            get {
                return ResourceManager.GetString("TXT_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string TXT_Save_Changes {
            get {
                return ResourceManager.GetString("TXT_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how far the mouse must move before considering sending an AutoClick.
        /// </summary>
        public static string TXT_Select_How_Far_Mouse_Should_Move_Before_Considering_To_Send_An_AutoClick {
            get {
                return ResourceManager.GetString("TXT_Select_How_Far_Mouse_Should_Move_Before_Considering_To_Send_An_AutoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the mouse button to simulate.
        /// </summary>
        public static string TXT_Select_The_Mouse_Button_To_Simulate {
            get {
                return ResourceManager.GetString("TXT_Select_The_Mouse_Button_To_Simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of click to simulate.
        /// </summary>
        public static string TXT_Select_The_Type_Of_Click_To_Simulate {
            get {
                return ResourceManager.GetString("TXT_Select_The_Type_Of_Click_To_Simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TXT_Settings {
            get {
                return ResourceManager.GetString("TXT_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the click selector form when mouse stops moving.
        /// </summary>
        public static string TXT_Show_Me_The_Click_Selector_Form_When_Mouse_Stops_Moving {
            get {
                return ResourceManager.GetString("TXT_Show_Me_The_Click_Selector_Form_When_Mouse_Stops_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this screen on startup.
        /// </summary>
        public static string TXT_Show_This_Screen_On_Startup {
            get {
                return ResourceManager.GetString("TXT_Show_This_Screen_On_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ErgoWizard on Startup.
        /// </summary>
        public static string TXT_ShowErgoWizardOnStartup {
            get {
                return ResourceManager.GetString("TXT_ShowErgoWizardOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string TXT_ShutDown {
            get {
                return ResourceManager.GetString("TXT_ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down RSI Warrior will disable all RSI prevention mechanisms. Are you sure you want to continue?.
        /// </summary>
        public static string TXT_Shutting_Down_Will_Stop_RSI_Warrior {
            get {
                return ResourceManager.GetString("TXT_Shutting_Down_Will_Stop_RSI_Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Click.
        /// </summary>
        public static string TXT_Single_Click {
            get {
                return ResourceManager.GetString("TXT_Single_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Deviation Duration.
        /// </summary>
        public static string TXT_StandardDeviationDuration {
            get {
                return ResourceManager.GetString("TXT_StandardDeviationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strain.
        /// </summary>
        public static string TXT_Strain {
            get {
                return ResourceManager.GetString("TXT_Strain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strain Level.
        /// </summary>
        public static string TXT_StrainLevel {
            get {
                return ResourceManager.GetString("TXT_StrainLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretches.
        /// </summary>
        public static string TXT_Stretches {
            get {
                return ResourceManager.GetString("TXT_Stretches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string TXT_Sun {
            get {
                return ResourceManager.GetString("TXT_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string TXT_Thu {
            get {
                return ResourceManager.GetString("TXT_Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for a break! Click here to start a stretch..
        /// </summary>
        public static string TXT_Time_To_Start_Stretch {
            get {
                return ResourceManager.GetString("TXT_Time_To_Start_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between reminders (minutes).
        /// </summary>
        public static string TXT_TimeBetweenReminders {
            get {
                return ResourceManager.GetString("TXT_TimeBetweenReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to display posture reminder (seconds).
        /// </summary>
        public static string TXT_TimeToDisplayPostureReminder {
            get {
                return ResourceManager.GetString("TXT_TimeToDisplayPostureReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Clicks.
        /// </summary>
        public static string TXT_TotalClicks {
            get {
                return ResourceManager.GetString("TXT_TotalClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Inputs.
        /// </summary>
        public static string TXT_TotalInputs {
            get {
                return ResourceManager.GetString("TXT_TotalInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Key Presses.
        /// </summary>
        public static string TXT_TotalKeyPresses {
            get {
                return ResourceManager.GetString("TXT_TotalKeyPresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Keys.
        /// </summary>
        public static string TXT_TotalKeys {
            get {
                return ResourceManager.GetString("TXT_TotalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Mouse Clicks.
        /// </summary>
        public static string TXT_TotalMouseClicks {
            get {
                return ResourceManager.GetString("TXT_TotalMouseClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Presses.
        /// </summary>
        public static string TXT_TotalPresses {
            get {
                return ResourceManager.GetString("TXT_TotalPresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Click.
        /// </summary>
        public static string TXT_Triple_Click {
            get {
                return ResourceManager.GetString("TXT_Triple_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string TXT_Tue {
            get {
                return ResourceManager.GetString("TXT_Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant Coefficient.
        /// </summary>
        public static string TXT_VariantCoefficient {
            get {
                return ResourceManager.GetString("TXT_VariantCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string TXT_Wednesday {
            get {
                return ResourceManager.GetString("TXT_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string TXT_Weekday {
            get {
                return ResourceManager.GetString("TXT_Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What distance of motion should not be considered an AutoClick.
        /// </summary>
        public static string TXT_What_Distance_Of_Motion_Should_Not_Be_Considered_An_AutoClick {
            get {
                return ResourceManager.GetString("TXT_What_Distance_Of_Motion_Should_Not_Be_Considered_An_AutoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What key will activate the click selector form?.
        /// </summary>
        public static string TXT_What_Key_Will_Activate_The_Click_Selector_Form {
            get {
                return ResourceManager.GetString("TXT_What_Key_Will_Activate_The_Click_Selector_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to keep your changes?.
        /// </summary>
        public static string TXT_Would_You_Like_To_Keep_Your_Changes {
            get {
                return ResourceManager.GetString("TXT_Would_You_Like_To_Keep_Your_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the wrong key. Please try again..
        /// </summary>
        public static string TXT_WrongKey {
            get {
                return ResourceManager.GetString("TXT_WrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please purchase RSI Warrior Full Edition to continue using these features....
        /// </summary>
        public static string TXT_YourEvaluationHasPeriodExpired {
            get {
                return ResourceManager.GetString("TXT_YourEvaluationHasPeriodExpired", resourceCulture);
            }
        }
    }
}
